### ISSUE TITLE
Rendering `data` in template has different results after upgrading to 0.10.0.

### ISSUE THREAD

**Issue by dinoperovic** [awesto/django-shop#537] opened 2017-04-05 14:09 UTC
I have an issue with rendering data in my product detail template after upgrading to 0.10.0.

I used to have the `{{ data }}` variable set up in my template to pass all the product data to javascript like so: `var PRODUCT = $.parseJSON('{{ data|rest_json|escapejs }}');`

After trying to upgrade the `{{ data }}` object has changed and now contains the entire **template_context** along side the product serialized data.

What used to be:
`{u'name': u'Trousers trend', u'url': 'http://localhost:8000/catalog/trousers-trend/', u'slug': u'trousers-trend'}`

is now:
`{u'paginator': <rest_framework.pagination.PageNumberPagination object at 0x1090d2290>, u'product': <Product: Trousers trend>, u'name': u'Trousers trend', u'url': 'http://localhost:8000/catalog/trousers-trend/', u'args': (), u'request': <rest_framework.request.Request object at 0x108bd1350>, u'edit_mode': False, u'kwargs': {u'slug': u'trousers-trend'}, u'response': <Response status_code=200, "text/html; charset=utf-8">, u'data': {...}, u'slug': u'trousers-trend', u'view': <shopit.views.product.ProductDetailView object at 0x108eafd50>}`

inside the data context variable. Also the serializer fields are accessible directly inside the context: `{{ name }}`, `{{ slug }}`...

I have managed to get around this by changing `renderers.CMSPageRenderer.render()` method.

I've changed:
`template_context = self.get_template_context(data, renderer_context)`
to:
`template_context = self.get_template_context({}, renderer_context)`

That way the serializer fields are not passed in directly to the context but only later added with:
`template_context['data'] = data`

I upgraded Django to version 1.10.7, Django CMS to 3.4.2 and django-rest-framework to 3.6.2 in the process.

Is this an issue for anyone else?

**Comment by rfleschenberg** [comment] 2017-04-05 14:22
This looks like a bug to me. This is probably my bad, I remember changing something related to this. I will look into it.

**Comment by jrief** [comment] 2017-04-10 09:55
I think this was fixed in this PR https://github.com/jrief/django-shop/tree/fixes/359-TypeError-RegexURLPattern

@dinoperovic please retest with that branch

This regression unfortunately was introduced by a code change required by an API change in DRF.

**Comment by dinoperovic** [comment] 2017-04-10 10:23
@jrief switching to https://github.com/jrief/django-shop/tree/fixes/359-TypeError-RegexURLPattern fixed it!

**Closed** 2017-04-10 12:03 UTC
Labels: bug
