### ISSUE TITLE
errors when starting tutorial

### ISSUE THREAD

**Issue by beckastar** [awesto/django-shop#335] opened 2016-04-15 02:07 UTC
I have my virtualenvironment, and I followed the installs step by step.  When I ran manage.py, I received the following import errors:

ImportError: No module named email_auth

I commented out the email_auth package in settings.py, and got a different error:

ImportError: No module named shop.search.routers

I imagine if I'm getting this error, others will, too.

**Comment by jrief** [comment] 2016-04-15 06:45
If email_auth can not be found, then I assume that django-shop is not in your Python search path.
did you execute?

```
(shoptutorial)$ cd django-shop
(shoptutorial)$ pip install -e .
```

the full instructions are here http://django-shop.readthedocs.org/en/latest/tutorial/intro.html

**Comment by rfleschenberg** [comment] 2016-04-15 19:18
Thank you for the report. If Jacob's suggestion doesn't fix the issue, can you please show us a transcript of your shell session?

**Comment by rfleschenberg** [comment] 2016-05-02 09:43
Closing for lack of reporter feedback. @beckastar, please open a new issue if you are still encountering problems. Thanks!

**Closed by rfleschenberg** 2016-05-02 09:43 UTC

**Comment by fe01134** [comment] 2016-12-23 02:45
I got the same error. I was using Python 2.7.   The error was pip install -e .
Obtaining file:///Users/carlosferreira/Documents/workspace/Tutorial/django-shop
    Complete output from command python setup.py egg_info:
    error in django-shop setup command: Invalid environment marker: python_version<"3.4"
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/carlosferreira/Documents/workspace/Tutorial/django-shop/

**Comment by rfleschenberg** [comment] 2016-12-23 08:49
@fe01134 please update your setuptools ans try again:

```
pip install -U setuptools
```

**Comment by MikhailNatalenko** [comment] 2018-05-20 07:50
When some of packets from tutorial has conflicts like this
 ```
django-haystack 2.5.0 has requirement Django<1.10, but you'll have django 1.10.8 which is incompatible.
django-allauth 0.35.0 has requirement Django>=1.11, but you'll have django 1.10.8 which is incompatible.
```

pip can't finish installation and some of modules are missed. 
Solve all conflicts first

**Comment by jrief** [comment] 2018-05-20 08:01
The canonical list of dependency requirements is shown the the Dockerfile build steps.
Since this obviously works, please compare it with your installation steps.
Also, since you did not specify a reproducible way how you attempted it, I can't give any help for now.

**Comment by MikhailNatalenko** [comment] 2018-05-20 08:05
I'm following Tutorial steps on OpenSuse Leap 42.3 Python 3.4.6

**Comment by MikhailNatalenko** [comment] 2018-05-20 08:18
Weird issue, it's look like some of packets just has not installed.
I fixed OP's touble with simply

```pip install django-email-auth```

Also this module missed too: 

```pip install djangoshop-stripe```

Now everything seems to be ok
