### ISSUE TITLE
Demo store not building or running

### ISSUE THREAD

**Issue by petedermott** [awesto/django-shop#431] opened 2016-09-30 13:46 UTC
I am trying to build a new django-shop app, as per the instructions at http://django-shop.readthedocs.io/en/latest/tutorial/intro.html and http://django-shop.readthedocs.io/en/latest/tutorial/quickstart.html#tutorial-quickstart

Here is my initial installation log.

```
(heroku) vagrant@vagrant:/vagrant/projects$ mkvirtualenv django-shop
Using base prefix '/usr'
New python executable in /home/vagrant/virtualenvs/django-shop/bin/python3.4
Also creating executable in /home/vagrant/virtualenvs/django-shop/bin/python
Installing setuptools, pip, wheel...done.
(django-shop) vagrant@vagrant:/vagrant/projects$ mkdir shop
(django-shop) vagrant@vagrant:/vagrant/projects$ cd shop
(django-shop) vagrant@vagrant:/vagrant/projects/shop$ git clone --depth 1 https://github.com/awesto/django-shop
Cloning into 'django-shop'...
remote: Counting objects: 521, done.
remote: Compressing objects: 100% (461/461), done.
remote: Total 521 (delta 52), reused 208 (delta 25), pack-reused 0
Receiving objects: 100% (521/521), 1.82 MiB | 87.00 KiB/s, done.
Resolving deltas: 100% (52/52), done.
Checking connectivity... done.
(django-shop) vagrant@vagrant:/vagrant/projects/shop$ cd django-shop
(django-shop) vagrant@vagrant:/vagrant/projects/shop/django-shop$ pip install -e .
Obtaining file:///vagrant/projects/shop/django-shop
Collecting Django>=1.9 (from django-shop==0.9.2)
  Using cached Django-1.10.1-py2.py3-none-any.whl
Collecting djangocms-cascade>=0.10.2 (from django-shop==0.9.2)
Collecting beautifulsoup4>=4.4.0 (from django-shop==0.9.2)
  Using cached beautifulsoup4-4.5.1-py3-none-any.whl
Collecting django-cms>=3.3.2 (from django-shop==0.9.2)
  Using cached django_cms-3.4.0-py2.py3-none-any.whl
Collecting django-post-office>=2.0.8 (from django-shop==0.9.2)
  Using cached django_post_office-2.0.8-py2.py3-none-any.whl
Collecting django-filer>=1.2.5 (from django-shop==0.9.2)
  Using cached django_filer-1.2.5-py2.py3-none-any.whl
Collecting django-ipware>=1.1.1 (from django-shop==0.9.2)
Collecting django-fsm>=2.4.0 (from django-shop==0.9.2)
Collecting django-fsm-admin>=1.2.3 (from django-shop==0.9.2)
Collecting djangorestframework>=3.2.5 (from django-shop==0.9.2)
  Using cached djangorestframework-3.4.7-py2.py3-none-any.whl
Collecting django-angular>=0.8.4 (from django-shop==0.9.2)
Collecting Django-Select2>=5.8.9 (from django-shop==0.9.2)
Collecting django-rest-auth>=0.5.0 (from django-shop==0.9.2)
Collecting django-admin-sortable2>=0.6.4 (from django-shop==0.9.2)
Collecting jsonfield (from djangocms-cascade>=0.10.2->django-shop==0.9.2)
Collecting django-formtools>=1.0 (from django-cms>=3.3.2->django-shop==0.9.2)
  Using cached django_formtools-1.0-py2.py3-none-any.whl
Collecting django-sekizai>=0.7 (from django-cms>=3.3.2->django-shop==0.9.2)
  Using cached django_sekizai-0.10.0-py2.py3-none-any.whl
Collecting django-treebeard>=4.0.1 (from django-cms>=3.3.2->django-shop==0.9.2)
Collecting djangocms-admin-style>=1.0 (from django-cms>=3.3.2->django-shop==0.9.2)
Collecting django-classy-tags>=0.7.2 (from django-cms>=3.3.2->django-shop==0.9.2)
  Using cached django_classy_tags-0.8.0-py2.py3-none-any.whl
Collecting Unidecode<0.05,>=0.04 (from django-filer>=1.2.5->django-shop==0.9.2)
Collecting django-mptt<0.9,>=0.6 (from django-filer>=1.2.5->django-shop==0.9.2)
  Using cached django_mptt-0.8.6-py2.py3-none-any.whl
Collecting django-polymorphic<0.9,>=0.7 (from django-filer>=1.2.5->django-shop==0.9.2)
  Using cached django_polymorphic-0.8.1-py2.py3-none-any.whl
Collecting easy-thumbnails<2.4,>=1.0 (from django-filer>=1.2.5->django-shop==0.9.2)
  Using cached easy_thumbnails-2.3-py2.py3-none-any.whl
Collecting django-appconf>=0.6.0 (from Django-Select2>=5.8.9->django-shop==0.9.2)
  Using cached django_appconf-1.0.2-py2.py3-none-any.whl
Collecting six>=1.9.0 (from django-rest-auth>=0.5.0->django-shop==0.9.2)
  Using cached six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in /home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages (from django-polymorphic<0.9,>=0.7->django-filer>=1.2.5->django-shop==0.9.2)
Collecting pillow (from easy-thumbnails<2.4,>=1.0->django-filer>=1.2.5->django-shop==0.9.2)
  Using cached Pillow-3.3.1-cp34-cp34m-manylinux1_x86_64.whl
Installing collected packages: Django, jsonfield, djangocms-cascade, beautifulsoup4, django-formtools, django-classy-tags, django-sekizai, django-treebeard, djangocms-admin-style, django-cms, django-post-office, Unidecode, django-mptt, django-polymorphic, pillow, easy-thumbnails, django-filer, django-ipware, django-fsm, django-fsm-admin, djangorestframework, django-angular, django-appconf, Django-Select2, six, django-rest-auth, django-admin-sortable2, django-shop
  Running setup.py develop for django-shop
Successfully installed Django-1.10.1 Django-Select2-5.8.9 Unidecode-0.4.19 beautifulsoup4-4.5.1 django-admin-sortable2-0.6.4 django-angular-0.8.4 django-appconf-1.0.2 django-classy-tags-0.8.0 django-cms-3.4.0 django-filer-1.2.5 django-formtools-1.0 django-fsm-2.4.0 django-fsm-admin-1.2.3 django-ipware-1.1.6 django-mptt-0.8.6 django-polymorphic-0.8.1 django-post-office-2.0.8 django-rest-auth-0.8.1 django-sekizai-0.10.0 django-shop django-treebeard-4.0.1 djangocms-admin-style-1.2.4 djangocms-cascade-0.10.2 djangorestframework-3.4.7 easy-thumbnails-2.3 jsonfield-1.0.3 pillow-3.3.1 six-1.10.0
(django-shop) vagrant@vagrant:/vagrant/projects/shop/django-shop$ pip install -r requirements/common.txt
Collecting beautifulsoup4==4.4.0 (from -r requirements/common.txt (line 1))
  Using cached beautifulsoup4-4.4.0-py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): django-admin-sortable2==0.6.4 in /home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages (from -r requirements/common.txt (line 2))
Collecting django-allauth==0.23.0 (from -r requirements/common.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): django-angular==0.8.4 in /home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages (from -r requirements/common.txt (line 4))
Collecting django-appconf==1.0.1 (from -r requirements/common.txt (line 5))
  Using cached django_appconf-1.0.1-py2.py3-none-any.whl
Collecting django-classy-tags==0.7.2 (from -r requirements/common.txt (line 6))
  Using cached django_classy_tags-0.7.2-py2.py3-none-any.whl
Collecting django-cms==3.3.2 (from -r requirements/common.txt (line 7))
  Using cached django_cms-3.3.2-py2.py3-none-any.whl
Collecting django-compressor==1.6 (from -r requirements/common.txt (line 8))
  Using cached django_compressor-1.6-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): django-filer==1.2.5 in /home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages (from -r requirements/common.txt (line 9))
Collecting django-filter==0.13.0 (from -r requirements/common.txt (line 10))
  Using cached django_filter-0.13.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): django-fsm==2.4.0 in /home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages (from -r requirements/common.txt (line 11))
Requirement already satisfied (use --upgrade to upgrade): django-fsm-admin==1.2.3 in /home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages (from -r requirements/common.txt (line 12))
Collecting django-haystack==2.5.0 (from -r requirements/common.txt (line 13))
Collecting django-ipware==1.1.1 (from -r requirements/common.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): django-mptt==0.8.6 in /home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages (from -r requirements/common.txt (line 15))
Collecting django-parler==1.6.4 (from -r requirements/common.txt (line 16))
  Using cached django_parler-1.6.4-py2.py3-none-any.whl
Collecting django-polymorphic==1.0.1 (from -r requirements/common.txt (line 17))
  Using cached django_polymorphic-1.0.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): django-post-office==2.0.8 in /home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages (from -r requirements/common.txt (line 18))
Collecting django-rest-auth==0.5.0 (from -r requirements/common.txt (line 19))
Collecting django-sass-processor==0.5.1 (from -r requirements/common.txt (line 20))
Requirement already satisfied (use --upgrade to upgrade): django-sekizai==0.10.0 in /home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages (from -r requirements/common.txt (line 21))
Requirement already satisfied (use --upgrade to upgrade): Django-Select2==5.8.9 in /home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages (from -r requirements/common.txt (line 22))
Collecting djangoshop-stripe==0.2.0 (from -r requirements/common.txt (line 23))
Collecting django-treebeard==4.0 (from -r requirements/common.txt (line 24))
Collecting djangocms-bootstrap3==0.1.1 (from -r requirements/common.txt (line 25))
Collecting djangocms-cascade==0.10.1 (from -r requirements/common.txt (line 26))
Collecting djangocms-text-ckeditor==3.0.1 (from -r requirements/common.txt (line 27))
  Using cached djangocms_text_ckeditor-3.0.1-py2.py3-none-any.whl
Collecting djangorestframework==3.2.5 (from -r requirements/common.txt (line 28))
  Using cached djangorestframework-3.2.5-py2.py3-none-any.whl
Collecting drf-haystack==1.5.6 (from -r requirements/common.txt (line 29))
Requirement already satisfied (use --upgrade to upgrade): easy-thumbnails==2.3 in /home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages (from -r requirements/common.txt (line 30))
Collecting elasticsearch==1.7.0 (from -r requirements/common.txt (line 31))
  Using cached elasticsearch-1.7.0-py2.py3-none-any.whl
Collecting html5lib==0.9999999 (from -r requirements/common.txt (line 32))
Requirement already satisfied (use --upgrade to upgrade): jsonfield==1.0.3 in /home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages (from -r requirements/common.txt (line 33))
Collecting libsass==0.8.3 (from -r requirements/common.txt (line 34))
Collecting oauthlib==1.0.3 (from -r requirements/common.txt (line 35))
Collecting Pillow==3.3.0 (from -r requirements/common.txt (line 36))
  Using cached Pillow-3.3.0-cp34-cp34m-manylinux1_x86_64.whl
Collecting pluggy==0.3.1 (from -r requirements/common.txt (line 37))
  Using cached pluggy-0.3.1-py2.py3-none-any.whl
Collecting py==1.4.30 (from -r requirements/common.txt (line 38))
  Using cached py-1.4.30-py2.py3-none-any.whl
Collecting Pygments==2.0.2 (from -r requirements/common.txt (line 39))
  Using cached Pygments-2.0.2-py3-none-any.whl
Collecting python-openid==2.2.5 (from -r requirements/common.txt (line 40))
Collecting pytz==2015.7 (from -r requirements/common.txt (line 41))
  Using cached pytz-2015.7-py2.py3-none-any.whl
Collecting requests==2.7.0 (from -r requirements/common.txt (line 42))
  Using cached requests-2.7.0-py2.py3-none-any.whl
Collecting requests-oauthlib==0.5.0 (from -r requirements/common.txt (line 43))
  Using cached requests_oauthlib-0.5.0-py2.py3-none-any.whl
Collecting six==1.9.0 (from -r requirements/common.txt (line 44))
  Using cached six-1.9.0-py2.py3-none-any.whl
Collecting stripe==1.37.0 (from -r requirements/common.txt (line 45))
  Using cached stripe-1.37.0-py3-none-any.whl
Collecting Unidecode==0.4.18 (from -r requirements/common.txt (line 46))
Collecting urllib3==1.12 (from -r requirements/common.txt (line 47))
  Using cached urllib3-1.12-py2.py3-none-any.whl
Collecting virtualenv==13.1.2 (from -r requirements/common.txt (line 48))
  Using cached virtualenv-13.1.2-py2.py3-none-any.whl
Collecting wheel==0.24.0 (from -r requirements/common.txt (line 49))
  Using cached wheel-0.24.0-py2.py3-none-any.whl
Collecting python3-openid>=3.0.1 (from django-allauth==0.23.0->-r requirements/common.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): Django>=1.6 in /home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages (from django-allauth==0.23.0->-r requirements/common.txt (line 3))
Requirement already satisfied (use --upgrade to upgrade): djangocms-admin-style>=1.0 in /home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages (from django-cms==3.3.2->-r requirements/common.txt (line 7))
Requirement already satisfied (use --upgrade to upgrade): django-formtools>=1.0 in /home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages (from django-cms==3.3.2->-r requirements/common.txt (line 7))
Collecting python-dateutil (from drf-haystack==1.5.6->-r requirements/common.txt (line 29))
  Using cached python_dateutil-2.5.3-py2.py3-none-any.whl
Collecting defusedxml (from python3-openid>=3.0.1->django-allauth==0.23.0->-r requirements/common.txt (line 3))
Installing collected packages: beautifulsoup4, defusedxml, python3-openid, oauthlib, requests, requests-oauthlib, django-allauth, six, django-appconf, django-classy-tags, django-treebeard, django-cms, django-compressor, django-filter, django-haystack, django-ipware, django-parler, django-polymorphic, djangorestframework, django-rest-auth, libsass, django-sass-processor, stripe, djangoshop-stripe, djangocms-bootstrap3, djangocms-cascade, Pillow, html5lib, djangocms-text-ckeditor, python-dateutil, drf-haystack, urllib3, elasticsearch, pluggy, py, Pygments, python-openid, pytz, Unidecode, virtualenv, wheel
  Found existing installation: beautifulsoup4 4.5.1
    Uninstalling beautifulsoup4-4.5.1:
      Successfully uninstalled beautifulsoup4-4.5.1
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Found existing installation: django-appconf 1.0.2
    Uninstalling django-appconf-1.0.2:
      Successfully uninstalled django-appconf-1.0.2
  Found existing installation: django-classy-tags 0.8.0
    Uninstalling django-classy-tags-0.8.0:
      Successfully uninstalled django-classy-tags-0.8.0
  Found existing installation: django-treebeard 4.0.1
    Uninstalling django-treebeard-4.0.1:
      Successfully uninstalled django-treebeard-4.0.1
  Found existing installation: django-cms 3.4.0
    Uninstalling django-cms-3.4.0:
      Successfully uninstalled django-cms-3.4.0
  Found existing installation: django-ipware 1.1.6
    Uninstalling django-ipware-1.1.6:
      Successfully uninstalled django-ipware-1.1.6
  Found existing installation: django-polymorphic 0.8.1
    Uninstalling django-polymorphic-0.8.1:
      Successfully uninstalled django-polymorphic-0.8.1
  Found existing installation: djangorestframework 3.4.7
    Uninstalling djangorestframework-3.4.7:
      Successfully uninstalled djangorestframework-3.4.7
  Found existing installation: django-rest-auth 0.8.1
    Uninstalling django-rest-auth-0.8.1:
      Successfully uninstalled django-rest-auth-0.8.1
  Found existing installation: djangocms-cascade 0.10.2
    Uninstalling djangocms-cascade-0.10.2:
      Successfully uninstalled djangocms-cascade-0.10.2
  Found existing installation: Pillow 3.3.1
    Uninstalling Pillow-3.3.1:
      Successfully uninstalled Pillow-3.3.1
  Found existing installation: Unidecode 0.4.19
    Uninstalling Unidecode-0.4.19:
      Successfully uninstalled Unidecode-0.4.19
  Found existing installation: wheel 0.30.0a0
    Uninstalling wheel-0.30.0a0:
      Successfully uninstalled wheel-0.30.0a0
Successfully installed Pillow-3.3.0 Pygments-2.0.2 Unidecode-0.4.18 beautifulsoup4-4.4.0 defusedxml-0.4.1 django-allauth-0.23.0 django-appconf-1.0.1 django-classy-tags-0.7.2 django-cms-3.3.2 django-compressor-1.6 django-filter-0.13.0 django-haystack-2.5.0 django-ipware-1.1.1 django-parler-1.6.4 django-polymorphic-1.0.1 django-rest-auth-0.5.0 django-sass-processor-0.5.1 django-treebeard-4.0 djangocms-bootstrap3-0.1.1 djangocms-cascade-0.10.1 djangocms-text-ckeditor-3.0.1 djangorestframework-3.2.5 djangoshop-stripe-0.2.0 drf-haystack-1.5.6 elasticsearch-1.7.0 html5lib-0.9999999 libsass-0.8.3 oauthlib-1.0.3 pluggy-0.3.1 py-1.4.30 python-dateutil-2.5.3 python-openid-2.2.5 python3-openid-3.0.10 pytz-2015.7 requests-2.7.0 requests-oauthlib-0.5.0 six-1.9.0 stripe-1.37.0 urllib3-1.12 virtualenv-13.1.2 wheel-0.24.0
(django-shop) vagrant@vagrant:/vagrant/projects/shop/django-shop$ npm install
django-shop@0.9.2 /vagrant/projects/shop/django-shop
├── angular@1.3.20
├── angular-animate@1.3.20
├── angular-bootstrap-plus@0.6.3
├── angular-i18n@1.3.20
├── angular-inview@1.5.7
├── angular-messages@1.3.20
├── angular-sanitize@1.3.20
├── angular-ui-bootstrap@0.13.4
├── bootstrap@3.3.7
├── bootstrap-sass@3.3.7
├── font-awesome@4.6.3
├── picturefill@3.0.2
└─┬ select2@4.0.3
  ├── almond@0.3.3
  └── jquery-mousewheel@3.1.13

(django-shop) vagrant@vagrant:/vagrant/projects/shop/django-shop$ cd example/
(django-shop) vagrant@vagrant:/vagrant/projects/shop/django-shop/example$ export DJANGO_SHOP_TUTORIAL=commodity
```

After this I run the `./manage.py initialize_shop_demo` and get the following error:

````
(django-shop) vagrant@vagrant:/vagrant/projects/shop/django-shop/example$ ./manage.py initialize_shop_demo
Traceback (most recent call last):
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/cmsplugin_cascade/cms_plugins.py", line 11, in <module>
    module_settings = import_module('{}.settings'.format(module))
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'cmsplugin_cascade.segmentation.settings'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/django/template/utils.py", line 65, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/django/template/backends/django.py", line 126, in get_package_libraries
    module = import_module(entry[1])
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/treebeard/templatetags/admin_tree_list.py", line 7, in <module>
    from treebeard.admin import TO_FIELD_VAR
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/treebeard/admin.py", line 6, in <module>
    from django.conf.urls import patterns, url
ImportError: cannot import name 'patterns'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/cms/admin/__init__.py", line 11, in <module>
    plugin_pool.plugin_pool.discover_plugins()
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/cms/plugin_pool.py", line 32, in discover_plugins
    load('cms_plugins')
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/cms/utils/django_load.py", line 57, in load
    get_module(app, modname, verbose, failfast)
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/cms/utils/django_load.py", line 41, in get_module
    module = import_module(module_name)
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/cmsplugin_cascade/cms_plugins.py", line 22, in <module>
    import_module('{}.cms_plugins'.format(module))
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/cmsplugin_cascade/segmentation/cms_plugins.py", line 19, in <module>
    class SegmentPlugin(TransparentMixin, CascadePluginBase):
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/cmsplugin_cascade/segmentation/cms_plugins.py", line 40, in SegmentPlugin
    default_template = Template('{% load cms_tags %}{% for plugin in instance.child_plugin_instances %}{% render_plugin plugin %}{% endfor %}')
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/django/template/base.py", line 184, in __init__
    engine = Engine.get_default()
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/functools.py", line 472, in wrapper
    result = user_function(*args, **kwds)
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/django/template/engine.py", line 74, in get_default
    django_engines = [engine for engine in engines.all()
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/django/template/utils.py", line 89, in all
    return [self[alias] for alias in self]
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/django/template/utils.py", line 89, in <listcomp>
    return [self[alias] for alias in self]
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/django/template/utils.py", line 80, in __getitem__
    engine = engine_cls(params)
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/django/template/backends/django.py", line 30, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/django/template/backends/django.py", line 48, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/django/template/backends/django.py", line 113, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/django/template/backends/django.py", line 130, in get_package_libraries
    "trying to load '%s': %s" % (entry[1], e)
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'treebeard.templatetags.admin_tree_list': cannot import name 'patterns'
```

**Comment by rfleschenberg** [comment] 2016-09-30 13:51
Thanks for reporting this. I can reproduce the problem. We will fix this ASAP.

**Comment by rfleschenberg** [comment] 2016-09-30 14:04
This looks like a problem because of incompatible dependencies (you end up with Django 1.10 in your virtualenv). Temporary workaround: `pip install 'Django<1.10'`.

I see two problems in our code related to this:

1) We should specify `'Django>=1.9,<1.10'` in `install_requires`.

2) Running `pip install -e .` after `pip install -r requirements/common.txt` might update dependencies. Maybe we should just revert the order of these commands in the documentation.

**Comment by khchine5** [comment] 2016-09-30 14:08
Yes , Django==1.10 isn't supported by Django-shop because djangocms-cascade doesn't support yet Django==1.10

**Comment by petedermott** [comment] 2016-09-30 14:29
It may also be worth noting that even after making this change scss files still have to be compiled  with a `./manage.py compilescss` in order to get the site to load. This also throws up some none blocking errors:

```
(django-shop) vagrant@vagrant:/vagrant/projects/shop/django-shop/example$ ./manage.py compilescss

Invalid template /home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/cmsplugin_cascade/templates/cascade/templatetags/section-selector.html: 'for' statements should have at least four words: for

Error parsing template /home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/menus/templates/menu/dummy.html: Invalid template name in 'extends' tag: ''. Got this from the 'template' variable.

Error parsing template /home/vagrant/virtualenvs/django-shop/lib/python3.4/site-packages/cms/templates/cms/dummy.html: Invalid template name in 'extends' tag: ''. Got this from the 'template' variable.
```

**Comment by rfleschenberg** [comment] 2016-09-30 16:21
@petedermott Thanks for pointing this out. I think these errors can be safely ignored.

**Comment by rfleschenberg** [comment] 2016-09-30 16:32
This should be fixed in the master branch now. If you still run into any problems, please file a new issue. Thanks for your help!

**Closed by rfleschenberg** 2016-09-30 16:32 UTC
Labels: accepted, blocker, bug, documentation

**Comment by jrief** [comment] 2016-09-30 16:38
@petedermott 
these are just warnings and should not prevent you from testing.
Anyway, yesterday I released django-sass-processor==0.5.1 which finds automatically all SASS include pathes.
Do you use it?

**Comment by pingyangtiaer** [comment] 2018-01-13 06:05
@petedermott Did you figured it out how to make it work?
@jrief I tried to change the setting in requirements/common.txt with "django-sass-processor==0.5.1",however, the "manage.py migrate" still giving the error "ImportError: No module named cmsplugin_cascade.utils" Any ideas?
Thanks,
Peter
pingyang.whu@gmail.com

**Comment by jrief** [comment] 2018-01-13 08:35
yesterday I created a version which is known to run:
```
git clone -b releases/0.13.x --depth 1 https://github.com/awesto/django-shop
cd django-shop
docker-compose up -d --build
```

Point a browser onto http://<docker-machines-ip>:9009/en/ 
If you you Docker on Mac, docker-machines-ip presumably is 192.168.99.100
